### ISSUE TITLE
advanced-ng16 README says checkout app's checkout component is standalone

### ISSUE THREAD

**Issue by keithcarter5** [edumserrano/module-federation-examples#15]

**Comment by keithcarter5** [comment]
I was confused at first when you said the checkout component in the checkout app was a standalone component...when i went into that app, it is not a standalone component.  I realize now you mean the checkout component in the shell app, which imports and wraps the remote checkout component.  I'm sorry for the unnecessary posting...very impressive repo, by the way!!  I will be following your work from now on!!

**Comment by keithcarter5** [comment]
As I said, I was previously confused, but I'm following now.  Sorry for the unnecessary post.

**Comment by keithcarter5** [comment]
OK...perhaps I was looking at the wrong version of this component and that caused my confusion, but I see now that the CheckoutComponent in the checkout app (of the advanced-ng16 demo) is indeed a standalone component...is it an issue if it is not a standalone component...I am running Angular 15 and I was planning on using this advanced-ng16 demo's strategy, but my components (that are being mounted by the shell) will not be angular standalone components.

**Comment by edumserrano** [comment]
Yes, if you're using Angular 15, you should be able to do everything equal in the `advanced-ng16` demo without using  Angular standalone components anywhere, on remotes or shell.

At the repo's README it says:
> The repo is structured as a learning guide to Webpack Module Federation. I advise you to go through each section in the order they are presented.

And one of the reasons it's because there's a build up to the `advanced-ng16` demo, so some of the doubts you might have are potentially explained in previous demo's. Even some concepts that aren't used in the `advanced-ng16` demo but are still useful to know about.

Point in case is that in the [component-standalone-ng16 code demo README](https://github.com/edumserrano/webpack-module-federation-with-angular/blob/main/code-demos/component-standalone-ng16/README.md) it does say:
> The approaches shown here are NOT limited to Angular standalone components. The same would work for non-standalone components.

It's fine if you want to focus on the `advanced-ng16` demo but if you're learning about module federation and what you can and cannot do, I'd advise you to take your time and explore the code demos and their READMEs in order.
