### ISSUE TITLE
Sharing services and data from shell to remotes

### ISSUE THREAD

**Issue by keithcarter5** [edumserrano/module-federation-examples#16]
I looked through this repo (and it's very impressive, by the way) looking for how you might have created services and/or data to provide to remotes for use.  It make sense that remotes might be (or should be) standalone, but sharing services would be useful.  Logging is a good example, where the host has a logger and wants remotes to utilize the host's logger service.

If you can point me to content that I may be overlooking, that would be great.  If not, I'd be very interested in your thoughts.

**Comment by edumserrano** [comment]
It seems to me that what you want to do is share code between your remotes which is done using shared libraries via the `Shared` configuration of module federation. I don't have an example of using a shared library in these code demos, I should have provided some information on this on the [Shared dependencies](https://github.com/edumserrano/webpack-module-federation-with-angular?tab=readme-ov-file#shared-dependencies) section of the main README, which takes you to the [Shared modules in Webpack Module Federation](https://github.com/edumserrano/webpack-module-federation-with-angular/blob/main/docs/shared.md) documentation.

Currently there's nothing in that documentation to talk about this but I'll have to add a section about it. What you want can be found at:

- At [module-federation/module-federation-examples](https://github.com/module-federation/module-federation-examples), which is one of the links provided at [Other learning material](https://github.com/edumserrano/webpack-module-federation-with-angular/blob/main/docs/other-learning-material.md#other-learning-material), you can look for examples where they also share a library. One of them is this one [angular15-microfrontends-lazy-components](https://github.com/module-federation/module-federation-examples/blob/master/angular15-microfrontends-lazy-components/README.md). The `mdmf-shared` project used in this code demo is where for instance you'd have your shared logging service. 
- [Using Module Federation with Nx Monorepos and Angular](https://www.angulararchitects.io/en/blog/using-module-federation-with-monorepos-and-angular/): It talks about monorepos but I think it's just because for these examples they have the shared code library in the same repo as the remotes and the shell. Similar to the code demo from the point above.
- [Module Federation — Sharing Library Code](https://medium.com/tenable-techblog/7-module-federation-sharing-library-code-759ae98f7fc8): perhaps this explains how sharing library code works in more depth.
- [Sharing Libs of a Monorepo](https://www.npmjs.com/package/@angular-architects/module-federation#sharing-libs-of-a-monorepo): some helps functions.

Note that you don't have to have all the code in the same repo and you can achieve what you want by sharing the common NPM package as a singleton across your shell and mfe. Your common package can provide the logging functions or even hold state. Here's another example where an auth package that holds state is used to provide login in the shell but also provide information about the logged in user to the remote: [Micro Frontends with Angular, Module Federation, and Auth0](https://auth0.com/blog/micro-frontends-with-angular-module-federation-and-auth0/).

**Comment by edumserrano** [comment]
See #17 for the updates I've made to the documentation.
